package seng201.team0.services.fileReaders;

import java.util.ArrayList;
import java.io.*;
import java.util.Scanner;


/**
 * This class uses the java utility Scanner to read through a provided CSV file. This useful for dynamic level
 * generation, allowing modification and adding new levels with different CSV files.
 *
 * @author Gordon Homewood
 *
 */
public class FileReader {

    private final ArrayList<ArrayList<Integer>> tileGridList;

    /**
     * Establishes a new file reader that reads through CSV file and creates 2D array. This constructor takes in a
     * grid of where certain level blocks should be placed.
     *
     * @param path path to CSV file
     * @param levelTilesWidth columns in 2D array
     * @param levelTilesHeight rows in 2D array
     *
     * @author Gordon Homewod
     */
    public FileReader(String path,int levelTilesWidth, int levelTilesHeight) {
        this.tileGridList = new ArrayList<ArrayList<Integer>>(); //Initializes list to store value in CSV/Grid cells
        Scanner sc = null;
        try {
            sc = new Scanner(new File(path));
            sc.useDelimiter(",");

            for (int i = 0; i < levelTilesHeight; i++) {
                //Loops thorough csv file
                ArrayList<Integer> innerList = new ArrayList<>(levelTilesWidth);
                for (int j = 0; j < levelTilesWidth; j++) {
                    if (sc.hasNext()) {
                        String value = sc.next().trim();
                        if (!value.isEmpty()) {
                            int num = Integer.parseInt(value);
                            innerList.add(num);
                        }
                    }
                }
                tileGridList.add(innerList);
            }

        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
        } finally {
            if(sc != null){
                sc.close();}

        }
    }

    /**
     * Establishes a new file reader that reads through CSV file and creates 2D array. This constructor takes in a
     * tuple-like point CSV file that is useful for reading cart animations from a CSV file. Sets numCoords to
     * 2, as there are only two valyes per row in the provided array - thus the reason for a different contrusctor.
     *
     * @param path path to CSV file
     * @param levelTilesHeight rows in 2D array
     *
     * @author Gordon Homewod
     */
    public FileReader(String path,int levelTilesHeight) {
        //System.out.print(path);
        //Constructor for loading path, sets to 2 because of 2 dimensions (x,y)
        int numCoords = 2;

        //Constructor that reads file of level
        this.tileGridList = new ArrayList<ArrayList<Integer>>(); //Intializes list to store value in CSV/Grid cells
        Scanner sc = null;
        try {
            sc = new Scanner(new File(path));
            sc.useDelimiter(",");

            for (int i = 0; i < levelTilesHeight; i++) {
                ArrayList<Integer> innerList = new ArrayList<>(numCoords);
                for (int j = 0; j < numCoords; j++) {
                    if (sc.hasNext()) {
                        String value = sc.next().trim();
                        if (!value.isEmpty()) {
                            int num = Integer.parseInt(value);
                            innerList.add(num);
                        }
                    }
                }
                tileGridList.add(innerList);
            }

        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
        } finally {
            if(sc != null){
                sc.close();}

        }
    }


    /**
     * @return list of 2D array generated by reading through CSV loader .
     *
     * @author Gordon Homewood
     */
    public ArrayList<ArrayList<Integer>> getList() {
        return this.tileGridList;
    }

}

